"""Generates the CLAUDE.upstream.md file for a downstream repo."""
from __future__ import annotations

from datetime import datetime, timezone

from upstreamiq.graph.models import ChangeEvent, ChangeKind, ExtractedSurface, Link, Repo
from upstreamiq.utils.fs import relative_time


def generate_capsule(
    downstream_repo: Repo,
    upstream_links: list[Link],
    surfaces: dict[str, ExtractedSurface],
    recent_changes: dict[str, list[ChangeEvent]],
) -> str:
    now = datetime.now(timezone.utc).isoformat()
    lines: list[str] = []

    lines += [
        "<!-- AUTO-GENERATED by RepoLink — DO NOT EDIT -->",
        f"<!-- Run: repolink sync  to refresh -->",
        f"<!-- Generated: {now} -->",
        "",
        f"# Upstream context for {downstream_repo.name}",
        "",
        "This file is auto-generated by RepoLink. It contains the minimum context",
        "your AI coding agent needs about upstream repositories.",
        "Import it in CLAUDE.md with: @CLAUDE.upstream.md",
        "",
        "---",
        "",
    ]

    for link in upstream_links:
        up_name = link.upstream
        surface = surfaces.get(up_name)
        changes = recent_changes.get(up_name, [])
        breaking_changes = [c for c in changes if c.kind == ChangeKind.BREAKING]

        lines.append(f"## {up_name}  [{link.link_type.value}]")
        lines.append("")

        if surface:
            time_ago = relative_time(surface.extracted_at)
            lines.append(f"> Last synced: {surface.commit_sha} · {time_ago}")
        else:
            lines.append("> Not yet extracted — run: repolink extract " + up_name)

        if breaking_changes:
            lines.append("> ⚠ BREAKING CHANGES in last 7 days — review before coding:")
            for bc in breaking_changes[:5]:
                before_after = ""
                if bc.before and bc.after:
                    before_after = f": {bc.before} → {bc.after}"
                lines.append(f">   - {bc.affected_symbol}{before_after}  (commit {bc.commit_sha[:8]}: {bc.commit_message[:60]})")

        lines.append("")

        if surface:
            # Types section
            if surface.exported_types:
                lang = _lang_for_code_block(surface)
                lines.append("### Exported types")
                lines.append("")
                lines.append(f"```{lang}")
                shown_types = surface.exported_types[:8]
                for typedef in shown_types:
                    if typedef.change_note:
                        lines.append(f"// ⚠ CHANGED: {typedef.change_note}")
                    lines.append(typedef.definition)
                    lines.append("")
                if len(surface.exported_types) > 8:
                    extra = len(surface.exported_types) - 8
                    lines.append(f"// ... and {extra} more types (run repolink show {up_name})")
                lines.append("```")
                lines.append("")

            # Endpoints section
            if surface.endpoints:
                lines.append("### API endpoints")
                lines.append("")
                shown_endpoints = surface.endpoints[:10]
                for ep in shown_endpoints:
                    change_note = f"  ⚠ {ep.change_note}" if ep.change_note else ""
                    lines.append(f"`{ep.method.upper()} {ep.path}`{change_note}")
                    if ep.description:
                        lines.append(f"  {ep.description}")
                    req = ep.request_schema or "—"
                    resp = ep.response_schema or "—"
                    if req != "—":
                        lines.append(f"  Request:  `{req}`")
                    if resp != "—":
                        lines.append(f"  Response: `{resp}`")
                    lines.append("")
                if len(surface.endpoints) > 10:
                    extra = len(surface.endpoints) - 10
                    lines.append(f"_... and {extra} more endpoints (run `repolink show {up_name}`)_")
                    lines.append("")

            # No types and no endpoints
            if not surface.exported_types and not surface.endpoints:
                lines.append("_No types or endpoints extracted._")
                lines.append(f"_Run `repolink extract {up_name}` for details._")
                lines.append("")

            # Consumer conventions
            if surface.consumer_conventions:
                lines.append("### Conventions for consumers")
                lines.append("")
                for conv in surface.consumer_conventions[:5]:
                    lines.append(f"- {conv}")
                lines.append("")

        lines.append("---")
        lines.append("")

    lines.append("<!-- End of upstream context | repolink.dev -->")

    content = "\n".join(lines)

    # Enforce 200-line limit by truncating middle if needed
    all_lines = content.splitlines()
    if len(all_lines) > 200:
        content = _truncate_to_limit(all_lines, upstream_links, surfaces, now, downstream_repo)

    return content


def _lang_for_code_block(surface: ExtractedSurface) -> str:
    """Determine code block language from repo name or surface data."""
    name_lower = surface.repo_name.lower()
    if any(kw in name_lower for kw in ("ts", "typescript", "next", "react", "node", "frontend", "mobile", "web")):
        return "typescript"
    if any(kw in name_lower for kw in ("py", "python", "api", "backend", "server", "fastapi", "django", "flask")):
        return "python"
    # Check type definitions for hints
    for t in surface.exported_types[:3]:
        defn = t.definition
        if "interface " in defn or "type " in defn or ": string" in defn:
            return "typescript"
        if "class " in defn and "BaseModel" in defn:
            return "python"
    return "typescript"


def _truncate_to_limit(
    all_lines: list[str],
    upstream_links: list[Link],
    surfaces: dict,
    now: str,
    downstream_repo: Repo,
) -> str:
    """Aggressively truncate to stay under 200 lines."""
    # Re-generate with fewer items per upstream
    lines: list[str] = [
        "<!-- AUTO-GENERATED by RepoLink — DO NOT EDIT -->",
        f"<!-- Run: repolink sync  to refresh -->",
        f"<!-- Generated: {now} -->",
        f"<!-- NOTE: Truncated to stay under 200 lines -->",
        "",
        f"# Upstream context for {downstream_repo.name}",
        "",
    ]

    for link in upstream_links:
        up_name = link.upstream
        surface = surfaces.get(up_name)
        lines.append(f"## {up_name}  [{link.link_type.value}]")
        lines.append("")

        if surface:
            time_ago = relative_time(surface.extracted_at)
            lines.append(f"> Last synced: {surface.commit_sha} · {time_ago}")
            lines.append("")

            if surface.exported_types:
                lang = _lang_for_code_block(surface)
                lines.append(f"```{lang}")
                for t in surface.exported_types[:4]:
                    lines.append(t.definition)
                    lines.append("")
                if len(surface.exported_types) > 4:
                    lines.append(f"// ... {len(surface.exported_types) - 4} more types (run repolink show {up_name})")
                lines.append("```")
                lines.append("")

            if surface.endpoints:
                for ep in surface.endpoints[:5]:
                    lines.append(f"`{ep.method.upper()} {ep.path}`")
                if len(surface.endpoints) > 5:
                    lines.append(f"_... and {len(surface.endpoints) - 5} more endpoints_")
                lines.append("")

        lines.append("---")
        lines.append("")

    lines.append("<!-- End of upstream context | repolink.dev -->")
    return "\n".join(lines)
