"""Generates a cross-repo TASK.md for a feature spanning multiple repos."""
from __future__ import annotations

from collections import defaultdict, deque
from datetime import datetime, timezone

from upstreamiq.graph.models import ExtractedSurface, Link, Repo


def generate_task_plan(
    task_description: str,
    all_repos: list[Repo],
    all_links: list[Link],
    surfaces: dict[str, ExtractedSurface],
) -> str:
    """Generate a topologically-ordered cross-repo task plan."""
    repo_map = {r.name: r for r in all_repos}
    ordered = _topological_sort(all_repos, all_links)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = [
        f"# Cross-repo task: {task_description}",
        f"# Generated by RepoLink | {now}",
        "# Start at the top — work through repos in order.",
        "",
        "## Change sequence",
        "",
        "| Step | Repo | Why this order |",
        "|------|------|----------------|",
    ]

    for i, repo_name in enumerate(ordered, 1):
        repo = repo_map[repo_name]
        upstreams = [l.upstream for l in all_links if l.downstream == repo_name]
        if not upstreams:
            reason = "No upstreams — start here"
        else:
            reason = f"Depends on {', '.join(upstreams)}"
        lines.append(f"| {i} | {repo_name} | {reason} |")

    lines.append("")
    lines.append("---")
    lines.append("")

    for i, repo_name in enumerate(ordered, 1):
        repo = repo_map[repo_name]
        upstreams = [l.upstream for l in all_links if l.downstream == repo_name]
        downstreams_of = [l.downstream for l in all_links if l.upstream == repo_name]

        lines.append(f"## Step {i}: {repo_name}")
        lines.append("")
        lines.append(f"Open a Claude Code session in: `{repo.path}`")
        lines.append("")

        if not upstreams:
            lines.append("No upstream dependencies for this repo.")
        else:
            lines.append(f"CLAUDE.upstream.md will contain context from: {', '.join(upstreams)}")
            if i > 1:
                prev_step = i - 1
                lines.append(f"After Step {prev_step} sync, CLAUDE.upstream.md will be updated automatically.")

        lines.append("")
        lines.append("**Suggested instruction for Claude Code:**")
        lines.append("")

        if not upstreams:
            instruction = (
                f'"{task_description} — start with the shared type definitions. '
                f"Add any new types, update existing ones for backward compatibility where possible.\""
            )
        else:
            upstream_context = ", ".join(f"CLAUDE.upstream.md ({u})" for u in upstreams)
            instruction = (
                f'"{task_description} — implement the changes in this repo. '
                f"The upstream context is already in your {upstream_context}. "
                f'Follow the existing patterns in this codebase."'
            )
        lines.append(f"  {instruction}")
        lines.append("")

        lines.append("**After completing:**")
        lines.append("")
        lines.append("  ```bash")
        lines.append("  repolink sync")
        lines.append("  ```")
        if downstreams_of:
            lines.append(f"  → This updates CLAUDE.upstream.md in: {', '.join(downstreams_of)}")
        if i < len(ordered):
            lines.append(f"  → Then move to Step {i + 1}.")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Verification checklist
    lines.append("## Verification checklist")
    lines.append("")
    for repo_name in ordered:
        repo = repo_map[repo_name]
        lang_hint = _verification_hint(repo.language)
        lines.append(f"- [ ] {repo_name}: {lang_hint}")
    lines.append("- [ ] End-to-end: feature works across the full stack")
    lines.append("")

    return "\n".join(lines)


def _topological_sort(repos: list[Repo], links: list[Link]) -> list[str]:
    """
    Return repo names in topological order (dependencies first).
    Repos that are depended on by others come first.
    """
    all_names = {r.name for r in repos}

    # Build adjacency: upstream → set of downstreams
    # In topological sort terms: upstream must come BEFORE downstream
    # So edge: upstream → downstream (upstream is a prerequisite)
    in_degree: dict[str, int] = {name: 0 for name in all_names}
    dependents: dict[str, list[str]] = defaultdict(list)

    for link in links:
        if link.upstream in all_names and link.downstream in all_names:
            dependents[link.upstream].append(link.downstream)
            in_degree[link.downstream] += 1

    # Kahn's algorithm
    queue = deque(sorted(name for name, degree in in_degree.items() if degree == 0))
    result: list[str] = []

    while queue:
        node = queue.popleft()
        result.append(node)
        for dependent in sorted(dependents[node]):
            in_degree[dependent] -= 1
            if in_degree[dependent] == 0:
                queue.append(dependent)

    # Handle cycles — append remaining nodes
    for name in sorted(all_names):
        if name not in result:
            result.append(name)

    return result


def _verification_hint(language: str) -> str:
    if language == "typescript":
        return "compiles without TypeScript errors"
    if language == "python":
        return "passes tests and type checks"
    if language == "go":
        return "builds without errors"
    if language == "rust":
        return "cargo build succeeds"
    return "no errors"
